Ai4Green_Api/Webapp/sources/blueprints/admin_dashboard/__init__.py
from flask import Blueprint

admin_dashboard_bp = Blueprint("admin_dashboard", __name__)

from . import routes

Ai4Green_Api/Webapp/sources/blueprints/admin_dashboard/routes.py
from datetime import datetime

from flask import Response, flash, redirect, render_template, url_for
from flask_login import login_required
from sources import models, services
from sources.auxiliary import (
    get_notification_number,
    get_workgroups,
    security_admin_only,
)
from sources.extensions import db

from . import admin_dashboard_bp


@admin_dashboard_bp.route("/admin_dashboard", methods=["GET", "POST"])
@admin_dashboard_bp.route(
    "/admin_dashboard/<request_institution>/<request_name>/<decision>",
    methods=["GET", "POST"],
)
@login_required
def admin_dashboard(
    request_institution: str = None, request_name: str = None, decision: str = None
) -> Response:
    """These routes display all active requests from database and perform the actions on approval/denial"""
    # must be logged in and admin
    workgroups = get_workgroups()
    notification_number = get_notification_number()
    if not security_admin_only():
        flash("You do not have permission to view this page")
        return redirect(url_for("main.index"))

    # if admin responds to a new workgroup request this block of code will process it and flash a message to the admin
    if request_institution:
        new_workgroup_request_message = handle_new_workgroup_request(
            request_institution, request_name, decision
        )
        flash(new_workgroup_request_message)

    # get data to populate the admin dashboard
    compound_data_error_reports = services.compound.get_compound_data_error_reports()
    reaction_count = services.reaction.count()
    compound_count = services.compound.count()
    new_workgroup_requests = services.workgroup.get_new_workgroup_requests()
    all_users = services.user.list_all()
    all_workgroups = services.workgroup.list_all()
    all_workbooks = services.workbook.list_all()
    recent_reactions = services.reaction.list_recent()

    return render_template(
        "admin_dashboard.html",
        workgroups=workgroups,
        compound_data_error_reports=compound_data_error_reports,
        number_compounds_in_db=compound_count,
        number_reactions_in_db=reaction_count,
        new_workgroup_requests=new_workgroup_requests,
        notification_number=notification_number,
        users=all_users,
        wgs=all_workgroups,
        workbooks=all_workbooks,
        recent_reactions=recent_reactions,
    )


def handle_new_workgroup_request(
    request_institution: str, request_name: str, decision: str
) -> str:
    """
    Processes the administrator's response to the new workgroup request. Either accepting or denying the request
    and updating the database accordingly.

    Args:
        request_institution - the name of the institution that the workgroup will be a part of
        request_name - the name of the new workgroup being requested
        decision - depends on button the admin clicks to either approve or deny the new workgroup

    Returns:
        message - to be flashed to admin to give feedback on the decision.

    """

    new_workgroup_request = (
        db.session.query(models.WorkGroupRequest)
        .join(models.WorkGroup)
        .filter(models.Institution.name == request_institution)
        .filter(models.WorkGroupRequest.name == request_name)
        .first()
    )
    if new_workgroup_request.status == "inactive":
        message = "This request has already been considered"
    else:
        message = "This request has not yet been considered"
        # set the request to inactive now it has been responded to
        new_workgroup_request.status = "inactive"
        approval_workgroup = new_workgroup_request.WorkGroup

        if decision == "deny":
            notification = models.Notification(
                person=new_workgroup_request.principal_investigator,
                type="Your Request to Create a Workgroup",
                info="Your Workgroup request for "
                + new_workgroup_request.name
                + " at "
                + new_workgroup_request.Institution.name
                + " has been denied.",
                time=datetime.now(),
                status="active",
                wg="",
                wb="",
                wg_request="",
            )
            db.session.add(notification)
            services.email.send_notification(new_workgroup_request.pi)
            message = "This request has been denied and workgroup removed"
            db.session.delete(approval_workgroup)
        if decision == "approve":
            # check if the workgroup has already been approved and if so return msg advising admin to check the db
            workgroup_already_approved = (
                db.session.query(models.WorkGroup)
                .filter(
                    models.Institution.name == new_workgroup_request.Institution.name
                )
                .filter(models.WorkGroup == new_workgroup_request.name)
                .filter(models.WorkGroup.approved is True)
                .first()
            )
            if workgroup_already_approved:
                new_workgroup_request.status = "active"
                message = "There was a problem with this request. Check the database for further details."
            # expected behaviour is to follow the else block as workgroup shouldn't be in requests if it is approved
            else:
                # When request has been approved the PI receives a notification and the workgroup approval status is updated
                notification = models.Notification(
                    person=new_workgroup_request.principal_investigator,
                    type="Your Request to Create a Workgroup",
                    info="Your Workgroup request for "
                    + new_workgroup_request.name
                    + " at "
                    + new_workgroup_request.Institution.name
                    + " has been approved.",
                    time=datetime.now(),
                    status="active",
                    wg="",
                    wb="",
                    wg_request="",
                )
                db.session.add(notification)
                services.email.send_notification(new_workgroup_request.pi)
                # update the workgroup approval status and flash message
                approval_workgroup.approved = True
                message = "This request has been approved"
        db.session.commit()
        return message

Ai4Green_Api/Webapp/sources/blueprints/create_workbook/__init__.py
from flask import Blueprint

create_workbook_bp = Blueprint("create_workbook", __name__)

from . import routes

Ai4Green_Api/Webapp/sources/blueprints/create_workbook/routes.py
from datetime import datetime

import pytz
from flask import redirect  # renders html templates
from flask import Response, flash, render_template, request, url_for
from flask_login import (  # protects a view function against anonymous users
    current_user,
    login_required,
)
from flask_wtf import FlaskForm
from sources import auxiliary, models
from sources.auxiliary import (
    get_notification_number,
    get_workgroups,
    remove_spaces_and_dashes,
    security_pi_sr_workgroup,
)
from sources.extensions import db
from sqlalchemy import func
from wtforms import StringField, SubmitField
from wtforms.validators import Length

from . import create_workbook_bp  # imports the blueprint of the dummy route


class CreateWorkbookForm(FlaskForm):
    """This form is used for creating a workbook"""

    workbook = StringField("Workbook", validators=[Length(min=4, max=140)])
    abbreviation = StringField(
        "3 letter abbreviation", validators=[Length(min=3, max=3)]
    )
    submit = SubmitField("Create Workbook", render_kw={"class": "btn btn-primary"})


@create_workbook_bp.route("/create_workbook/<workgroup>", methods=["GET", "POST"])
@login_required
def create_workbook(workgroup: str) -> Response:
    # must be logged in and a SR or PI of the workgroup
    if not security_pi_sr_workgroup(workgroup):
        flash("You do not have permission to view this page")
        return redirect(url_for("main.index"))
    """Creates a workbook using a FlaskForm. The book is created by a PI or SR and they must provide the name
    and workgroup the workbook should belong to"""
    workgroups = get_workgroups()
    notification_number = get_notification_number()
    form = CreateWorkbookForm()

    wg = (
        db.session.query(models.WorkGroup)
        .filter(models.WorkGroup.name == workgroup)
        .first()
    )
    # on valid submit
    if request.method == "POST" and form.validate_on_submit():
        # validates against special characters in workbook name
        workbook_name = auxiliary.sanitise_user_input(form.workbook.data)
        workbook_name_delimiters_removed = remove_spaces_and_dashes(workbook_name)
        if not workbook_name.replace(" ", "").replace("-", "").isalnum():
            flash("Workgroup names cannot contain special characters!")
            return render_template(
                "create_workgroup.html", form=form, workgroups=workgroups
            )

        # make sure workbook of same name does exist within workbook
        existing_workbook_names = (
            db.session.query(models.WorkBook)
            .join(models.WorkGroup)
            .filter(models.WorkGroup.id == wg.id)
            .all()
        )
        if [
            x
            for x in existing_workbook_names
            if remove_spaces_and_dashes(x.name).lower()
            == workbook_name_delimiters_removed.lower()
        ]:
            flash("A workbook of this name already exists!")
            return render_template(
                "create_workbook.html",
                form=form,
                workgroups=workgroups,
                notification_number=notification_number,
                workgroup=workgroup,
            )

        # validate workbook abbreviation
        workbook_abbreviation = auxiliary.sanitise_user_input(form.abbreviation.data)
        if not workbook_abbreviation.isalnum():
            flash("Workbook abbreviation must only consist of alphanumeric characters!")
            return render_template(
                "create_workbook.html",
                form=form,
                workgroups=workgroups,
                notification_number=notification_number,
                workgroup=workgroup,
            )
        existing_abbreviations = (
            db.session.query(models.WorkBook)
            .filter(
                func.lower(models.WorkBook.abbreviation)
                == workbook_abbreviation.lower()
            )
            .join(models.WorkGroup)
            .filter(models.WorkGroup.id == wg.id)
            .first()
        )
        if existing_abbreviations:
            flash("A workbook with this abbreviation already exists!")
            return render_template(
                "create_workbook.html",
                form=form,
                workgroups=workgroups,
                notification_number=notification_number,
                workgroup=workgroup,
            )

        # find user object
        user_obj = (
            db.session.query(models.Person)
            .join(models.User)
            .filter(models.User.email == current_user.email)
            .one()
        )

        # Create new workbook
        current_time = datetime.now(pytz.timezone("Europe/London")).replace(tzinfo=None)
        workbook = models.WorkBook(
            name=workbook_name,
            abbreviation=workbook_abbreviation,
            group=wg.id,
            users=[user_obj],
            time_of_creation=current_time,
        )
        db.session.add(workbook)
        db.session.commit()

        wb_obj = (
            db.session.query(models.WorkBook)
            .filter(models.WorkBook.name == workbook_name)
            .join(models.WorkGroup)
            .filter(models.WorkGroup.name == workgroup)
            .first()
        )
        # flash success message and redirect to manage workgroup page
        flash("Workbook has been created!")
        return redirect(
            url_for(
                "manage_workbook.manage_workbook",
                workgroup=workgroup,
                has_request="no",
                workbook=wb_obj.id,
            )
        )
    else:
        return render_template(
            "create_workbook.html",
            form=form,
            workgroups=workgroups,
            notification_number=notification_number,
            workgroup=workgroup,
        )

Ai4Green_Api/Webapp/sources/blueprints/create_workgroup/__init__.py
from flask import Blueprint

create_workgroup_bp = Blueprint("create_workgroup", __name__)

from . import routes

Ai4Green_Api/Webapp/sources/blueprints/delete_profile/__init__.py
from flask import Blueprint

delete_profile_bp = Blueprint("delete_profile", __name__)

from . import routes

Ai4Green_Api/Webapp/sources/blueprints/join_workgroup/__init__.py
from flask import Blueprint

join_workgroup_bp = Blueprint("join_workgroup", __name__)

from . import routes

Ai4Green_Api/Webapp/sources/blueprints/join_workgroup/routes.py
from datetime import datetime

from flask import redirect  # renders html templates
from flask import Response, flash, render_template, url_for
from flask_login import (  # protects a view function against anonymous users
    current_user,
    login_required,
)
from sources import models, services
from sources.auxiliary import get_notification_number, get_workgroups
from sources.extensions import db

from . import join_workgroup_bp  # imports the blueprint of the dummy route
from .forms import JoinWorkgroupForm


# put routes here
@join_workgroup_bp.route("/join_workgroup", methods=["GET", "POST"])
@login_required
def join_workgroup() -> Response:
    # must be logged in
    workgroups_dropdown = get_workgroups()
    notification_number = get_notification_number()
    # create the form
    form = JoinWorkgroupForm()
    # find all the workgroups in the WorkGroup database
    workgroups = db.session.query(models.WorkGroup).all()
    # add to list and add choices to form
    workgroup_list = [name.name for name in workgroups]

    form.workgroups.choices = workgroup_list
    # when it is validly submitted
    if form.validate_on_submit():
        # get workgroup selected
        workgroup = form.workgroups.data
        # check if user is already part of workgroup, if so flash message rerender template
        if workgroup in workgroups_dropdown:
            flash("You are already a member of this workgroup!")
            return render_template(
                "join_workgroup.html",
                form=form,
                workgroups=workgroups,
                notification_number=notification_number,
            )
        # find all the PIs for the workgroup
        pis = (
            db.session.query(models.Person)
            .join(models.Person.workgroup_principal_investigator)
            .filter(models.WorkGroup.name == workgroup)
            .all()
        )

        wg = (
            db.session.query(models.WorkGroup)
            .filter(models.WorkGroup.name == workgroup)
            .first()
        )

        # find person
        person = (
            db.session.query(models.Person)
            .join(models.User)
            .filter(models.User.email == current_user.email)
            .first()
        )

        # check to see if there is already an active request to join this workgroup from this user
        duplicates = (
            db.session.query(models.WGStatusRequest)
            .join(models.Person, models.WGStatusRequest.person == models.Person.id)
            .join(models.User)
            .filter(models.User.email == current_user.email)
            .join(models.WorkGroup)
            .filter(models.WorkGroup.id == wg.id)
            .filter(models.WGStatusRequest.status == 'active')
            .all()
        )
        if duplicates:
            flash(
                "You have already submitted a membership request for this workgroup. You will receive a notification "
                "when your request has been considered."
            )
            return redirect(url_for("main.index"))
        for pi in pis:
            notification = models.Notification(
                person=pi.id,
                type="New Workgroup Membership Request",
                info="You have a new request for a member to join Workgroup, "
                + workgroup
                + ", of which you are Principal Investigator.",
                time=datetime.now(),
                status="active",
                wg=wg.name,
                wb="",
                wg_request="",
            )
            services.email.send_notification(pi)
            db.session.add(notification)
            db.session.commit()  # Have to commit to get the id for notification
            wg_request = models.WGStatusRequest(
                principal_investigator=pi.id,
                person=person.id,
                wg=wg.id,
                current_role="Non-Member",
                new_role="Standard Member",
                time=datetime.now(),
                status="active",
                notification=notification.id,
            )
            db.session.add(wg_request)
        db.session.commit()
        flash(
            "Your membership has been requested. You will receive a notification when your request has been considered."
        )
        return redirect(url_for("main.index"))
    return render_template(
        "join_workgroup.html",
        form=form,
        workgroups=workgroups_dropdown,
        notification_number=notification_number,
    )

Ai4Green_Api/Webapp/sources/templates/_novel_compound.html
<div  id="js-novel-compound-input-form">
    <div>
       {{ component }} {{ number }} not in database. <br> <br>
    </div>
    <label> Name:<sup>*</sup> <input type="text"  id="js-new-compound-name" value="{{ name }}" placeholder="Required" class="no_autosave"> </label>
    <label> MW: <input type="text" id="js-new-compound-mw" value="{{ mw }}"> </label>
    <label> Hazard Codes: <input type="text" id="js-new-compound-hazards"  placeholder="Optional (HXXX-etc.)" class="no_autosave"> </label>
    <label> CAS: <input type="text" id="js-new-compound-cas"  placeholder="Optional" class="no_autosave"> </label>
    <label> Density (g/mL): <input type="text" id="js-new-compound-density" placeholder="Optional" class="no_autosave"> </label>
    <label> Conc. (M): <input type="text" id="js-new-compound-concentration" placeholder="Optional" class="no_autosave"> </label>
    <input  id="js-new-compound-smiles" hidden value="{{ smiles }}">
    <button class="btn btn-outline-dark" id="js-new-compound-submit" onclick="novelCompoundDataFromSketcher()"> Input </button>
</div>
<p><b><sup>*</sup>IUPAC names are auto-generated by <a href="https://cactus.nci.nih.gov/chemical/structure" target="_blank">Chemical Identity Resolver</a>
    and <a href="https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00512-4" target="_blank">STOUT</a></b></p>
<p id="new-compound-feedback"></p>

Ai4Green_Api/Webapp/sources/templates/_saved_reactions.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/reaction_list.css') }}">
<script>
    $(function() {
        if (window.location.pathname.split("/")[1] !== 'search') {
            showSavedReactionsSchemes()
        }
    });
</script>
</head>
{% if reactions %}

<div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label onclick="sortReactionsAlphabetically()" for="sort-a-z" class="btn btn-secondary btn-sm{% if sort_crit == "AZ" %} active{% else %}{% endif %}" id="AZ">
    <input value="1" type="radio" name="options" id="sort-a-z" autocomplete="off"{% if sort_crit == "AZ" %} checked{% else %}{% endif %} /> A-Z &#8645;
  </label>
  <label onclick="sortReactionsByTime()" for="sort-time" class="btn btn-secondary btn-sm{% if sort_crit == "time" %} active{% else %}{% endif %}" id="time">
    <input value="2" type="radio" name="options" id="sort-time" autocomplete="off"{% if sort_crit == "time" %} checked{% else %}{% endif %} /> Date Created (Newest First) &#8645;
  </label>
</div>

<div id="reaction-list">
    {% for reaction in reactions %}
        <div id="reaction-{{ loop.index }}" class="reaction-card">
            <div id="reaction-name{{ loop.index }}" class="reaction-name"><h4>{{ reaction.name }}</h4></div>
            <div id="reaction-id{{ loop.index }}"><h5>{{ reaction.reaction_id }}</h5></div>
            <div class="description">{{ reaction.description }}</div>
            <div id="image{{ loop.index }}"></div>
            <div class="reaction-time">Created: {{ reaction.time_of_creation[:-7] }}</div>
            <div class="reaction-time">Edited: {{ reaction.time_of_update[:-7] }}</div>
            <button
                    id="{{ reaction.reaction_id }}" onclick="redirectToReloadReaction(this)" class="btn btn-success reload-btn"
                    data-workgroup="{{ reaction.workgroup }}" data-workbook="{{ reaction.workbook }}">Reload
            </button>
            {% if reaction.creator_email == current_user.email %}
                <button
                        id="{{ reaction.reaction_id }}" onclick="deleteReaction(this)" name="delete-reaction" class="btn btn-danger"
                        data-workgroup="{{ reaction.workgroup }}" data-workbook="{{ reaction.workbook }}">Delete
                </button>
            {% endif %}
            {% if reaction.completion_status == "complete" %}
                <i class="fa fa-lock" style="font-size:20px; color:darkgrey;"></i><b style="font-size:12px; color:darkgrey;">  Reaction Locked</b>
            {% endif %}
            {% if reaction.creator_email != current_user.email %}
                <i class="fa fa-lock" style="font-size:20px; color:darkgrey;"></i><b style="font-size:12px; color:darkgrey;">  Read-only reaction created by {{ reaction.creator_username }}</b>
            {% endif %}
            {% if reaction.addenda %}
                <i class="bi bi-chat-dots" style="font-size:20px; color:darkgrey;"></i><b style="font-size:12px; color:darkgrey;">  Contains Amendments</b>
            {% endif %}
            <hr class="line">
        </div>
    {% endfor %}
</div>
{% else %}

{% endif %}
<input type="hidden" value="{{ reactions|length }}" id="js-number-of-reactions">
<input type="hidden" value="{{ sort_crit }}" id="js-sort-crit">

Ai4Green_Api/Webapp/sources/templates/confirm_user_removal.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Confirm removal of user from workgroup and/or books</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
           {{ confirmation_message|safe }}
        </p>
        <p>
            {{ form.approve }} {{ form.deny }}<br>
        </p>
    </form>
</div>
{% endblock %}

Ai4Green_Api/Webapp/sources/templates/element_sustainability.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2 style="text-align:center">Periodic Table of Element Sustainability</h2>
    <img class="img-big" src="/static/element_sustainability_periodic_table.jpg" alt="Remaining years until depletion of known reserves of elements">
    Image from reference: J. Hunt, A. S. Matharu, A. H. King and J. H. Clark, <i>Green Chem.</i>, 2015, <strong>17</strong>, 1949–1950.
</div>
{% endblock %}

Ai4Green_Api/Webapp/sources/templates/manage_workbook.html
{% extends "base.html" %}
{% block content %}
<div id="container" class="container">
    <h2>Manage Workbooks</h2>
    <br>
    <p><b>Workgroup Name: {{ current_workgroup }}</b></p>
    {% if not workbook %}
    <p>No workbooks to show</p>
    {% else %}
    <p>Select a workbook to begin:</p>
    {{ form.workbooks() }}<br><br>

    <ul id="myTab" class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link {% if has_request == "no" %}active{% endif %}" role="tab" data-toggle="tab" href="#overview" aria-selected="{% if has_request == "no" %}true{% else %}false{% endif %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if has_request == "yes" %}active{% endif %}" role="tab" data-toggle="tab" href="#requests" aria-selected="{% if has_request == "no" %}false{% else %}true{% endif %}">Requests</a>
        </li>
    </ul>
    <div class="tab-content">
<!-- Overview table-->
        <div class="tab-pane fade {% if has_request == "no" %}show active{% else %}in{% endif %}" id="overview" role="tabpanel">
            <br>
            <table id="manage_workgroup_table" class="table table-bordered table-sm">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Email
                    </th>
                    <th colspan="3">
                        Action
                    </th>
                </tr>
                <tr>
                    <th colspan="5">
                        Workbook Members
                    </th>
                </tr>
                {% for member in members %}
                <tr>
                    <td class="align-middle">
                        {{ member.user.fullname }}
                    </td>
                    <td class="align-middle">
                        {{ member.user.email }}
                    </td>
                    <td class="align-middle">
                        <button id="remove{{ loop.index }}" value="{{ member.user.email }}" class="btn btn-danger" onclick="make_change('remove{{ loop.index }}', 'remove')" style="width:220px;">&#8595; Remove From Workbook</button>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th colspan="5">
                        Other Members in Workgroup
                    </th>
                </tr>
                {% for other_member in other_members %}
                <tr>
                    <td class="align-middle">
                        {{ other_member.user.fullname }}
                    </td>
                    <td class="align-middle">
                        {{ other_member.user.email }}
                    </td>
                    <td class="align-middle">
                        <button id="add{{ loop.index }}" value="{{ other_member.user.email }}" class="btn btn-primary" onclick="make_change('add{{ loop.index }}', 'add')" style="width:220px;">&#8593; Add to Workbook</button>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <br>
        </div>
<!--Requests table-->
        <div class="tab-pane fade {% if has_request == "no" %}in{% else %}show active{% endif %}" id="requests" role="tabpanel">
            <br>
            {% if requests %}
            <table id="manage_workgroup_request_table" class="table table-striped table-sm">
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Request
                    </th>
                    <th>
                        Time
                    </th>
                    <th>
                        Decision
                    </th>
                </tr>
                {% for request in requests %}
                <tr>
                    <td class="align-middle">
                        {{ request.Person.user.fullname }}
                    </td>
                    <td class="align-middle">
                        {{ request.Person.user.email }}
                    </td>
                    <td class="align-middle">
                        Join Workbook
                    </td>
                    <td class="align-middle">
                        {% set time = request.time|string %}
                        {{ time[:-7] }}
                    </td>
                    <td class="align-middle">
                        <button id="request_approve{{ loop.index }}" value="{{ request.Person.user.email }}" class="btn btn-primary" onclick="make_change_request('request_approve{{ loop.index }}', 'approve')" style="width:110px;">Approve</button>
                        <button id="request_deny{{ loop.index }}" value="{{ request.Person.user.email }}" class="btn btn-primary" onclick="make_change_request('request_deny{{ loop.index }}', 'deny')" style="width:110px;">Deny</button>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
            <p>You currently have no requests.</p>
            {% endif %}
        </div>
    </div>
    <br>
    {% endif %}
    <a href="{{url_for('create_workbook.create_workbook', workgroup=current_workgroup)}}" id="create-workbook-button" class="btn btn-success">Create Workbook</a>
<input type="hidden" id="current_workgroup" value="{{ current_workgroup }}">
</div>
<script>
    // when workbooks dropdown is changed, the list of workbook users is updated
    // manage_workgroup/book
    $(document).on('change', '#workbooks', function(url) {
        let workbook = $("#workbooks").val();
        let workgroup = $("#current_workgroup").val()
        window.location.href = "/manage_workbook/" + workgroup + "/no/" + workbook;
    });
    function make_change(id, mode){
        let workbook = $("#workbooks").val();
        let workgroup = $("#current_workgroup").val()
        let email = $("#" + id).val()
        fetch('/manage_workbook/' +  workgroup + '/' + workbook + '/' + email + '/' + mode).then(function(response) {
            response.json().then(function(data) {
                alert(data.feedback);
                window.location.href = "/manage_workbook/" + workgroup + "/" + "no/" + workbook;
            });
        });
    }
     function make_change_request(id, mode){
        let workbook = $("#workbooks").val();
        let workgroup = $("#current_workgroup").val();
        let email = $("#" + id).val()
        fetch('/manage_workbook_request/' + workgroup + "/" + workbook + '/' + email + '/' + mode).then(function(response) {
            response.json().then(function(data) {
                alert(data.feedback);
                window.location.href = "/manage_workbook/" + workgroup + "/yes/" + workbook;
            });
        });
    }
</script>
{% endblock %}

Ai4Green_Api/Webapp/sources/templates/workgroup_membership_summary.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <h2>Workgroup Membership Summary</h2>
    <br>
    <form action="" method="POST">
        Workgroups: <br>
        {{ form.csrf_token }}
        {{ form.workgroups }} <br><br>
        {{ form.submit(class_="btn btn-primary") }}<br>
    </form>
    No workgroups shown? Click <a id="join-workgroup" href="{{ url_for('join_workgroup.join_workgroup') }}">here</a> to join a workgroup.<br><br>
    {% if workbooks is defined %}
    Workgroup Selected:<br>
    <b>{{ workgroup }}</b><br><br>
    You are a member of the following workbooks within this workgroup:<br>
    {% for workbook in workbooks %}
    <b>{{ workbook }}</b><br>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}